
// async action types
export const ASYNC_START = 'ASYNC_START'
export const ASYNC_END = 'ASYNC_END'

// user action types
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED'
export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED'
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED'

// landing action aypes
export const REDIRECT = 'REDIRECT'
export const APP_LOAD = 'APP_LOAD'
export const SET_PAGE = "SET_PAGE"
export const CHANGE_TAB = "CHANGE_TAB"
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED'
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED'

// post action aypes
export const ADD_POST = 'ADD_POST'
export const GET_POST = 'GET_POST'
export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_BY_HANDLE = 'GET_POSTS_BY_HANDLE'
export const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY'
export const POST_LOADING = 'POST_LOADING'
export const POSTS_LOADING = 'POSTS_LOADING'
export const DELETE_POST = 'DELETE_POST'
export const POST_PAGE_LOADED = 'POST_PAGE_LOADED'
export const POST_PAGE_UNLOADED = 'POST_PAGE_UNLOADED'
export const POST_FAVORITED = 'POST_FAVORITED'
export const POST_UNFAVORITED = 'POST_UNFAVORITED'
export const SET_COMMENTS_FILTER = 'SET_COMMENTS_FILTER'
export const SET_POSTS_FILTER = 'SET_POSTS_FILTER'
export const APPLY_TAG_FILTER = "APPLY_TAG_FILTER"
export const POST_SUBMITTED = 'POST_SUBMITTED'

// note action types
export const ADD_COMMENT = 'ADD_COMMENT'
export const GET_COMMENT = 'GET_COMMENT'
export const GET_COMMENTS = 'GET_COMMENTS'
export const COMMENT_LOADING = 'COMMENT_LOADING'
export const COMMENTS_LOADING = 'COMMENTS_LOADING'
export const DELETE_COMMENT = 'DELETE_COMMENT'

// profile action types
export const ADD_PROFILE = 'ADD_PROFILE'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILES_LOADING = 'PROFILES_LOADING'
export const GET_PROFILE_HANDLE = 'GET_PROFILE_HANDLE'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const DELETE_PROFILE = 'DELETE_PROFILE'
export const PROFILE_PAGE_LOADED = "PROFILE_PAGE_LOADED"
export const PROFILE_PAGE_UNLOADED = "PROFILE_PAGE_UNLOADED"
export const PROFILE_FAVORITES_PAGE_LOADED = "PROFILE_FAVORITES_PAGE_LOADED"
export const PROFILE_FAVORITES_PAGE_UNLOADED = "PROFILE_FAVORITES_PAGE_UNLOADED"
export const SET_PROFILES_FILTER = 'SET_PROFILES_FILTER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
export const USERS_POSTS_LOADING = 'USERS_POSTS_LOADING'

// settings action types
export const SETTINGS_SAVED = 'SETTINGS_SAVED'
export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED'
export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED'
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED'
export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'
export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR'

// errors action types
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
